---
- hosts: cluster #1

  tasks:
    - name: Apt-get update
      apt:
        update_cache: yes

    - name: Apt-get dist-upgrade
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - debug:
        msg: Reboot is required!
      when: reboot_required.stat.exists

    - name: Reboot host
      include_role:
        name: reboot_host
      when: reboot_required.stat.exists and reboot_ok

    - name: "Apt-get autoremove"
      apt:
        autoremove: yes
